export const categories = [
  ["cities", "🌆", "Cities"], ["countries", "🌍", "Countries"],
  ["animals", "🐶", "Animals"], ["food", "🍕", "Food"],
  ["drinks", "🥤", "Drinks"], ["sport", "🏀", "Sport"],
  ["football", "⚽", "Football"], ["movies", "🎬", "Movies"],
  ["tv-shows", "📺", "TV Shows"], ["music", "🎵", "Music"],
  ["video-games", "🎮", "Video Games"], ["famous-people", "⭐", "Famous People"],
  ["jobs", "💼", "Jobs"], ["school", "📚", "School"],
  ["nature", "🌿", "Nature"], ["landmarks-places", "🏛️", "Landmarks & Places"],
  ["transport", "🚗", "Transport"], ["objects", "💡", "Objects"],
  ["brands", "🛍️", "Brands"], ["random-mix", "🎲", "Random Mix"],
].map(([id, icon, name]) => ({ id, icon, name }));

const codePoint = (emoji) => Array.from(emoji)
  .map((character) => character.codePointAt(0).toString(16))
  .filter((part) => part !== "fe0f")
  .join("-");

const clue = (word, emoji, alt = `A clear illustration of ${word}`) => ({
  word,
  image: `./assets/clues/${codePoint(emoji)}.svg`,
  alt,
  emoji,
});

const definitions = {
  cities: [
    ["Gold Coast", [["gold", "🥇", "A shiny gold medal"], ["coast", "🏖️", "A sandy coastline"]], "A city on Australia's east coast."],
    ["Newcastle", [["new", "✨", "Bright new sparkles"], ["castle", "🏰", "A stone castle"]], "A city in north-east England."],
    ["Blackpool", [["black", "⬛", "A solid black square"], ["pool", "🏊", "A swimmer in a pool"]], "A seaside town in Lancashire."],
    ["Oxford", [["ox", "🐂", "A strong ox"], ["ford", "🌊", "A shallow river crossing"]], "A university city in southern England."],
    ["Cape Town", [["cape", "🦸", "A superhero wearing a flowing cape"], ["town", "🏘️", "A small group of town houses"]], "A city beneath Table Mountain."],
    ["Bangkok", [["bang", "💥", "A sudden comic-style bang"], ["cock", "🐓", "A crowing cockerel"]], "The capital city of Thailand."],
    ["Melbourne", [["mail", "✉️", "A sealed piece of mail"], ["born", "👶", "A newborn baby"]], "A major city in southern Australia."],
    ["New Delhi", [["new", "✨", "Bright new sparkles"], ["deli", "🥪", "A deli sandwich"]], "The capital city of India."],
    ["Hamburg", [["ham", "🍖", "A joint of ham"], ["burg", "🍔", "A burger"]], "A large port city in Germany."],
    ["Belfast", [["bell", "🔔", "A ringing bell"], ["fast", "🏎️", "A fast racing car"]], "The capital city of Northern Ireland."],
  ],
  countries: [
    ["Iceland", [["ice", "🧊", "A cube of ice"], ["land", "🏝️", "A small piece of land"]], "A Nordic island country."],
    ["Finland", [["fin", "🦈", "A shark fin above the water"], ["land", "🏝️", "A small piece of land"]], "A country in northern Europe."],
    ["Poland", [["pole", "🚩", "A flag on a tall pole"], ["land", "🏝️", "A small piece of land"]], "A country in central Europe."],
    ["Japan", [["jar", "🫙", "A glass storage jar"], ["pan", "🍳", "A frying pan"]], "An island country in East Asia."],
    ["Thailand", [["tie", "👔", "A smart necktie"], ["land", "🏝️", "A small piece of land"]], "A country in South-East Asia."],
    ["Denmark", [["den", "🕳️", "A dark animal den"], ["mark", "✅", "A clear check mark"]], "A country in northern Europe."],
    ["Ireland", [["eye", "👁️", "A human eye"], ["land", "🏝️", "A small piece of land"]], "An island country west of Great Britain."],
    ["New Zealand", [["new", "✨", "Bright new sparkles"], ["sea", "🌊", "A curling sea wave"], ["land", "🏝️", "A small piece of land"]], "An island country in the South Pacific."],
    ["Singapore", [["sing", "🎤", "A singer at a microphone"], ["pour", "🫗", "A drink being poured"]], "A city-state in South-East Asia."],
    ["Switzerland", [["Swiss", "🧀", "A wedge of Swiss cheese"], ["land", "🏝️", "A small piece of land"]], "A mountainous country in central Europe."],
  ],
  animals: [
    ["Butterfly", [["butter", "🧈", "A block of butter"], ["fly", "🪰", "A housefly"]], "An insect with colourful wings."],
    ["Starfish", [["star", "⭐", "A bright five-pointed star"], ["fish", "🐟", "A blue fish"]], "A sea animal with five arms."],
    ["Seahorse", [["sea", "🌊", "A curling sea wave"], ["horse", "🐴", "A horse's head"]], "A tiny upright sea animal."],
    ["Catfish", [["cat", "🐈", "A standing cat"], ["fish", "🐟", "A blue fish"]], "A fish named for its whiskers."],
    ["Jellyfish", [["jelly", "🍮", "A wobbling jelly dessert"], ["fish", "🐟", "A blue fish"]], "A soft sea animal with tentacles."],
    ["Dragonfly", [["dragon", "🐉", "A green dragon"], ["fly", "🪰", "A housefly"]], "A fast-flying insect often seen near water."],
    ["Bulldog", [["bull", "🐂", "A strong bull"], ["dog", "🐕", "A friendly dog"]], "A stocky breed of dog."],
    ["Hedgehog", [["hedge", "🌳", "A thick green hedge"], ["hog", "🐖", "A pink hog"]], "A small spiny mammal."],
    ["Swordfish", [["sword", "🗡️", "A sharp sword"], ["fish", "🐟", "A blue fish"]], "A large fish with a long pointed bill."],
    ["Firefly", [["fire", "🔥", "A bright fire"], ["fly", "🪰", "A housefly"]], "A small beetle that glows at night."],
  ],
  food: [
    ["Pancake", [["pan", "🍳", "A frying pan"], ["cake", "🎂", "A decorated cake"]], "A flat breakfast food."],
    ["Cupcake", [["cup", "🥤", "A drinking cup"], ["cake", "🎂", "A decorated cake"]], "A small individual cake."],
    ["Popcorn", [["pop", "💥", "A comic-style pop burst"], ["corn", "🌽", "An ear of corn"]], "A crunchy cinema snack."],
    ["Cheeseburger", [["cheese", "🧀", "A wedge of cheese"], ["burger", "🍔", "A burger in a bun"]], "A burger topped with cheese."],
    ["Meatball", [["meat", "🥩", "A cut of meat"], ["ball", "⚽", "A round ball"]], "A small round serving of minced meat."],
    ["Hotdog", [["hot", "🔥", "A bright flame"], ["dog", "🐕", "A friendly dog"]], "A sausage served in a long bun."],
    ["Fishcake", [["fish", "🐟", "A blue fish"], ["cake", "🎂", "A decorated cake"]], "A savoury patty made with fish."],
    ["Doughnut", [["dough", "🥖", "A piece of bread dough"], ["nut", "🥜", "A peanut"]], "A ring-shaped sweet treat."],
    ["Pineapple", [["pine", "🌲", "A pine tree"], ["apple", "🍎", "A red apple"]], "A spiky tropical fruit."],
    ["Eggplant", [["egg", "🥚", "A white egg"], ["plant", "🪴", "A green potted plant"]], "A purple vegetable also called aubergine."],
  ],
  drinks: [
    ["Milkshake", [["milk", "🥛", "A glass of milk"], ["shake", "🤝", "Two hands shaking"]], "A cold, creamy drink."],
    ["Lemonade", [["lemon", "🍋", "A yellow lemon"], ["aid", "🩹", "A first-aid plaster"]], "A sweet citrus drink."],
    ["Fruit Punch", [["fruit", "🍎", "A red apple representing fruit"], ["punch", "👊", "A clenched fist throwing a punch"]], "A mixed fruit drink."],
    ["Hot Chocolate", [["hot", "🔥", "A bright flame"], ["chocolate", "🍫", "A bar of chocolate"]], "A warm, sweet drink."],
    ["Iced Tea", [["ice", "🧊", "A cube of ice"], ["tea", "🍵", "A cup of tea"]], "Tea served cold."],
    ["Ginger Beer", [["ginger", "🫚", "A piece of ginger root"], ["beer", "🍺", "A glass of beer"]], "A fizzy drink flavoured with ginger."],
    ["Apple Juice", [["apple", "🍎", "A red apple"], ["juice", "🧃", "A carton of juice"]], "A fruit drink made from apples."],
    ["Coconut Water", [["coconut", "🥥", "A split coconut"], ["water", "💧", "A drop of water"]], "A clear drink found inside coconuts."],
    ["Green Tea", [["green", "🟩", "A solid green square"], ["tea", "🍵", "A cup of tea"]], "A light drink made from tea leaves."],
    ["Peppermint Tea", [["pepper", "🌶️", "A pepper"], ["mint", "🌿", "Fresh mint leaves"], ["tea", "🍵", "A cup of tea"]], "A caffeine-free herbal drink."],
  ],
  sport: [
    ["Basketball", [["basket", "🧺", "A woven basket"], ["ball", "🏀", "An orange ball"]], "A court sport played through a hoop."],
    ["Baseball", [["base", "🧱", "A solid building base"], ["ball", "⚾", "A white stitched ball"]], "A bat-and-ball sport."],
    ["Skateboard", [["skate", "⛸️", "An ice skate"], ["board", "🪵", "A wooden board"]], "A wheeled board used for tricks."],
    ["Table Tennis", [["table", "🪑", "A table and chair"], ["tennis", "🎾", "A tennis ball"]], "A fast indoor racket sport."],
    ["Volleyball", [["volley", "🙌", "Hands volleying upwards"], ["ball", "🏐", "A striped ball"]], "A net sport with six players per side."],
    ["Handball", [["hand", "✋", "An open hand"], ["ball", "⚽", "A round ball"]], "A fast team sport played by throwing a ball."],
    ["Kickboxing", [["kick", "🦵", "A leg kicking"], ["boxing", "🥊", "A boxing glove"]], "A combat sport using punches and kicks."],
    ["Ice Hockey", [["ice", "🧊", "A cube of ice"], ["hockey", "🏒", "A hockey stick and puck"]], "A fast team sport played on a frozen rink."],
    ["Water Polo", [["water", "💧", "A drop of water"], ["polo", "👕", "A polo shirt"]], "A team ball sport played in a swimming pool."],
    ["Motorsport", [["motor", "⚙️", "A turning motor gear"], ["sport", "🏁", "A chequered racing flag"]], "Competitive racing with powered vehicles."],
  ],
  football: [
    ["Goalkeeper", [["goal", "🥅", "A football goal"], ["key", "🔑", "A golden key"], ["keeper", "🧍", "A person standing guard"]], "The player allowed to use their hands."],
    ["Red Card", [["red", "🟥", "A bright red square"], ["card", "🃏", "A playing card"]], "A referee shows this for a sending-off."],
    ["Half Time", [["half", "🌓", "A moon split exactly in half"], ["time", "⏰", "An alarm clock"]], "The break in the middle of a match."],
    ["Corner Kick", [["corner", "📐", "A right-angle corner"], ["kick", "🦵", "A leg kicking"]], "A restart taken from beside the corner flag."],
    ["Football Boot", [["football", "⚽", "A black and white football"], ["boot", "🥾", "A sturdy boot"]], "A studded shoe worn on the pitch."],
    ["Hat Trick", [["hat", "🎩", "A top hat"], ["trick", "🪄", "A magician's wand"]], "Three goals scored by one player in a match."],
    ["Free Kick", [["free", "🕊️", "A bird flying freely"], ["kick", "🦵", "A leg kicking"]], "A set-piece awarded after a foul."],
    ["Clean Sheet", [["clean", "🧽", "A cleaning sponge"], ["sheet", "📄", "A clean sheet of paper"]], "A match in which a team concedes no goals."],
    ["Goal Line", [["goal", "🥅", "A football goal"], ["line", "➖", "A straight line"]], "The boundary a football must completely cross to score."],
    ["Yellow Card", [["yellow", "🟨", "A bright yellow square"], ["card", "🃏", "A playing card"]], "A referee's formal warning to a player."],
  ],
  movies: [
    ["Star Wars", [["star", "⭐", "A bright star"], ["wars", "⚔️", "Two crossed swords"]], "A space-film saga."],
    ["The Lion King", [["lion", "🦁", "A lion's face"], ["king", "👑", "A gold crown"]], "An animated royal adventure."],
    ["Toy Story", [["toy", "🧸", "A teddy bear toy"], ["story", "📖", "An open storybook"]], "A film about toys that come alive."],
    ["Spider-Man", [["spider", "🕷️", "A black spider"], ["man", "👨", "A man's face"]], "A web-slinging superhero film."],
    ["Black Panther", [["black", "⬛", "A solid black square"], ["panther", "🐆", "A large spotted cat"]], "A superhero film set in Wakanda."],
    ["School of Rock", [["school", "🏫", "A school building"], ["rock", "🪨", "A grey rock"]], "A comedy about a teacher who forms a student band."],
    ["The Jungle Book", [["jungle", "🌴", "A dense tropical jungle"], ["book", "📖", "An open book"]], "A story about a boy raised in the jungle.", ["Jungle Book"]],
    ["Space Jam", [["space", "🚀", "A rocket in space"], ["jam", "🍯", "A jar of sweet fruit jam"]], "A film mixing basketball with cartoon characters."],
    ["Chicken Run", [["chicken", "🐔", "A chicken"], ["run", "🏃", "A person running"]], "An animated escape adventure from a chicken farm."],
    ["The Karate Kid", [["karate", "🥋", "A martial arts uniform"], ["kid", "🧒", "A child"]], "A film about a young martial arts student.", ["Karate Kid"]],
  ],
  "tv-shows": [
    ["Love Island", [["love", "❤️", "A red heart"], ["island", "🏝️", "A tropical island"]], "A reality show set in a villa."],
    ["Dragon's Den", [["dragon", "🐉", "A green dragon"], ["den", "🕳️", "A dark animal den"]], "Entrepreneurs pitch ideas to investors."],
    ["Doctor Who", [["doctor", "🧑‍⚕️", "A doctor"], ["who", "❓", "A large question mark"]], "A time-travelling science-fiction show."],
    ["Stranger Things", [["stranger", "🕵️", "A mysterious stranger"], ["things", "📦", "A box of assorted things"]], "A supernatural show set in Hawkins."],
    ["Top Gear", [["top", "🏔️", "The top of a mountain"], ["gear", "⚙️", "A metal gear"]], "A motoring show about cars and challenges."],
    ["Breaking Bad", [["breaking", "💔", "Something breaking apart"], ["bad", "👎", "A thumbs-down sign"]], "A crime drama about a chemistry teacher."],
    ["Taskmaster", [["task", "✅", "A completed task"], ["master", "👑", "A master's crown"]], "A comedy show built around unusual challenges."],
    ["MasterChef", [["master", "👑", "A master's crown"], ["chef", "👨‍🍳", "A chef"]], "A competitive television cooking show."],
    ["The Masked Singer", [["masked", "🎭", "A theatrical mask"], ["singer", "🎤", "A singer at a microphone"]], "Celebrities sing while hidden inside costumes.", ["Masked Singer"]],
    ["Peaky Blinders", [["peak", "🏔️", "A sharp mountain peak"], ["blinders", "🪟", "A window covered by blinds"]], "A period crime drama set in Birmingham."],
  ],
  music: [
    ["Rock Star", [["rock", "🪨", "A grey rock"], ["star", "⭐", "A bright star"]], "A famous popular musician."],
    ["Drumstick", [["drum", "🥁", "A marching drum"], ["stick", "🪵", "A wooden stick"]], "A tool used to play percussion."],
    ["Keyboard", [["key", "🔑", "A golden key"], ["board", "🪵", "A wooden board"]], "An electronic instrument with black and white keys."],
    ["Headphones", [["head", "🙂", "A smiling head"], ["phones", "📱", "Two mobile phones"]], "You wear these to listen privately."],
    ["Playlist", [["play", "▶️", "A triangular play button"], ["list", "📋", "A clipboard list"]], "A chosen sequence of songs."],
    ["Soundcheck", [["sound", "🔊", "A loud speaker"], ["check", "✅", "A check mark"]], "A test musicians do before a live performance."],
    ["Bassline", [["bass", "🐟", "A bass fish"], ["line", "➖", "A straight line"]], "A low musical part that anchors a song."],
    ["Soundtrack", [["sound", "🔊", "A loud speaker"], ["track", "🛤️", "A railway track"]], "Music written or selected for a film or game."],
    ["Love Song", [["love", "❤️", "A red heart"], ["song", "🎤", "A singer performing a song"]], "A song about romantic feelings."],
    ["Boy Band", [["boy", "👦", "A boy"], ["band", "🎸", "A band playing music"]], "A vocal group made up of young male singers."],
  ],
  "video-games": [
    ["Minecraft", [["mine", "⛏️", "A mining pickaxe"], ["craft", "🛠️", "Crafting tools"]], "A block-building survival game."],
    ["Fortnite", [["fort", "🏰", "A strong fort"], ["night", "🌙", "A crescent moon at night"]], "A colourful battle royale game."],
    ["Mario Kart", [["Mario", "👨‍🔧", "A moustached mechanic in a red cap"], ["kart", "🏎️", "A racing kart"]], "A racing game with famous Nintendo characters."],
    ["Rocket League", [["rocket", "🚀", "A space rocket"], ["league", "🏆", "A league trophy"]], "A game that mixes cars and football."],
    ["Candy Crush", [["candy", "🍬", "A wrapped sweet"], ["crush", "💥", "A colourful crushing impact"]], "A match-three puzzle game."],
    ["Animal Crossing", [["animal", "🐶", "A friendly animal"], ["crossing", "🚸", "A marked crossing"]], "A relaxed village-life game with animal neighbours."],
    ["Fall Guys", [["fall", "🍂", "A falling leaf"], ["guys", "👥", "A group of people"]], "A colourful obstacle-course party game."],
    ["Sea of Thieves", [["sea", "🌊", "A curling sea wave"], ["thieves", "🥷", "A masked thief"]], "A multiplayer pirate adventure."],
    ["Guitar Hero", [["guitar", "🎸", "An electric guitar"], ["hero", "🦸", "A superhero"]], "A rhythm game played with a guitar controller."],
    ["Overwatch", [["over", "⬆️", "An arrow going over something"], ["watch", "⌚", "A wristwatch"]], "A team-based hero action game."],
  ],
  "famous-people": [
    ["Taylor Swift", [["tailor", "🪡", "A tailor's sewing needle"], ["swift", "🐦", "A swift bird in flight"]], "A singer-songwriter with an Eras tour."],
    ["Tiger Woods", [["tiger", "🐅", "A tiger"], ["woods", "🌲", "A group of woodland trees"]], "A famous golfer."],
    ["Tom Cruise", [["tom", "🐈", "A tom cat"], ["cruise", "🛳️", "A cruise ship"]], "An actor known for Mission: Impossible."],
    ["Will Smith", [["wheel", "🎡", "A giant wheel"], ["smith", "⚒️", "A blacksmith's hammer and pick"]], "An actor known for Men in Black."],
    ["Jack Black", [["jack", "🃏", "A jack playing card"], ["black", "⬛", "A solid black square"]], "An actor and musician from School of Rock."],
    ["Ice Cube", [["ice", "🧊", "A cube of ice"], ["cube", "🧊", "A solid cube"]], "A rapper and actor."],
    ["Post Malone", [["post", "📮", "A post box"], ["melon", "🍈", "A melon"]], "A singer and rapper known for Circles."],
    ["Katy Perry", [["cat", "🐈", "A cat"], ["pear", "🍐", "A pear"]], "A pop singer known for Roar."],
    ["Snoop Dogg", [["snoop", "🕵️", "A detective snooping around"], ["dog", "🐕", "A dog"]], "A rapper with a famously canine stage name."],
    ["Bear Grylls", [["bear", "🐻", "A bear"], ["grills", "🍖", "Food cooking on a grill"]], "An adventurer and survival television presenter."],
  ],
  jobs: [
    ["Firefighter", [["fire", "🔥", "A bright fire"], ["fighter", "🥊", "A boxing glove"]], "A person who tackles fires and rescues people."],
    ["Hairdresser", [["hair", "💇", "A haircut"], ["dresser", "🗄️", "A chest of drawers"]], "A person who cuts and styles hair."],
    ["Zookeeper", [["zoo", "🦓", "A zebra at the zoo"], ["keeper", "🧍", "A person caring for something"]], "A person who cares for animals at a zoo."],
    ["Bus Driver", [["bus", "🚌", "A yellow bus"], ["driver", "🧑‍✈️", "A uniformed driver"]], "A person who takes passengers along a route."],
    ["Window Cleaner", [["window", "🪟", "A glass window"], ["cleaner", "🧽", "A cleaning sponge"]], "A person who washes glass for a living."],
    ["Blacksmith", [["black", "⬛", "A solid black square"], ["smith", "⚒️", "A blacksmith's hammer and pick"]], "A craftsperson who shapes hot metal."],
    ["Bookkeeper", [["book", "📕", "A closed book"], ["keeper", "🧍", "A person keeping records"]], "A person who maintains financial records."],
    ["Dog Walker", [["dog", "🐕", "A dog"], ["walker", "🚶", "A person walking"]], "A person paid to exercise other people's pets."],
    ["Taxi Driver", [["taxi", "🚕", "A yellow taxi"], ["driver", "🧑‍✈️", "A uniformed driver"]], "A person who drives passengers for a fare."],
    ["Shopkeeper", [["shop", "🏪", "A small shop"], ["keeper", "🧍", "A person keeping watch"]], "A person who owns or manages a shop."],
  ],
  school: [
    ["Homework", [["home", "🏠", "A house"], ["work", "🔨", "A work hammer"]], "Learning tasks completed away from school."],
    ["Textbook", [["text", "💬", "A speech bubble with writing marks"], ["book", "📕", "A closed book"]], "A book used for studying a subject."],
    ["Playground", [["play", "🛝", "Children's play equipment"], ["ground", "🌱", "Green shoots growing from the ground"]], "An outdoor school area used at break."],
    ["Classroom", [["class", "👩‍🏫", "A teacher leading a class"], ["room", "🚪", "A door into a room"]], "The place where a lesson happens."],
    ["Timetable", [["time", "⏰", "An alarm clock"], ["table", "🪑", "A table and chair"]], "A schedule of lessons."],
    ["Whiteboard", [["white", "⬜", "A solid white square"], ["board", "🪵", "A wooden board"]], "A classroom surface used for writing and demonstrating."],
    ["Schoolbag", [["school", "🏫", "A school building"], ["bag", "🎒", "A backpack"]], "A bag used to carry books and equipment."],
    ["Lunchbox", [["lunch", "🥪", "A lunchtime sandwich"], ["box", "📦", "A box"]], "A container used to bring food to school."],
    ["Headteacher", [["head", "🙂", "A person's head"], ["teacher", "👩‍🏫", "A teacher"]], "The teacher responsible for leading a school."],
    ["School Trip", [["school", "🏫", "A school building"], ["trip", "🚌", "A bus leaving on a trip"]], "A class visit to learn somewhere away from school."],
  ],
  nature: [
    ["Sunflower", [["sun", "☀️", "A bright yellow sun"], ["flower", "🌼", "A yellow flower"]], "A tall plant with a large yellow head."],
    ["Waterfall", [["water", "💧", "A drop of water"], ["fall", "🍂", "A falling autumn leaf"]], "Water dropping over a steep edge."],
    ["Rainbow", [["rain", "🌧️", "A cloud releasing rain"], ["bow", "🎀", "A tied bow"]], "A colourful arc seen after rain."],
    ["Snowflake", [["snow", "❄️", "A snow crystal"], ["flake", "🥣", "A bowl of cereal flakes"]], "A tiny ice crystal that falls from clouds."],
    ["Moonlight", [["moon", "🌙", "A crescent moon"], ["light", "💡", "A glowing light bulb"]], "Natural light seen at night."],
    ["Earthquake", [["earth", "🌍", "Planet Earth"], ["quake", "🫨", "A face shaking strongly"]], "A sudden shaking of the ground."],
    ["Thunderstorm", [["thunder", "⚡", "A bolt of lightning"], ["storm", "⛈️", "A storm cloud"]], "A storm with thunder and lightning."],
    ["Sandstorm", [["sand", "🏜️", "A sandy desert"], ["storm", "⛈️", "A storm cloud"]], "Strong wind carrying a cloud of sand."],
    ["Starlight", [["star", "⭐", "A bright star"], ["light", "💡", "A glowing light bulb"]], "Light that travels from distant stars."],
    ["Wildflower", [["wild", "🦁", "A wild animal"], ["flower", "🌼", "A yellow flower"]], "A flower growing naturally without being planted."],
  ],
  "landmarks-places": [
    ["Tower Bridge", [["tower", "🗼", "A tall tower"], ["bridge", "🌉", "A bridge at dusk"]], "A famous bascule bridge in London."],
    ["Central Park", [["central", "🎯", "The centre of a target"], ["park", "🏞️", "A green public park"]], "A huge city park in Manhattan."],
    ["Golden Gate Bridge", [["golden", "🥇", "A gold medal"], ["gate", "🚪", "An open gate"], ["bridge", "🌉", "A bridge at dusk"]], "A red suspension bridge in San Francisco."],
    ["Sydney Opera House", [["Sydney", "🇦🇺", "The flag of Australia"], ["opera", "🎭", "Theatre masks"], ["house", "🏠", "A house"]], "A sail-shaped performing arts venue."],
    ["Stonehenge", [["stone", "🪨", "A heavy stone"], ["hinge", "🚪", "A door swinging on a hinge"]], "A prehistoric stone circle in Wiltshire."],
    ["Times Square", [["times", "⏰", "Several clocks showing different times"], ["square", "🟦", "A blue square"]], "A brightly lit public square in New York City."],
    ["White House", [["white", "⬜", "A solid white square"], ["house", "🏠", "A house"]], "The official home of the United States president."],
    ["Hyde Park", [["hide", "🙈", "A face hiding from view"], ["park", "🏞️", "A green public park"]], "A large royal park in central London."],
    ["Yellowstone", [["yellow", "🟨", "A bright yellow square"], ["stone", "🪨", "A heavy stone"]], "A famous national park in the United States."],
    ["Buckingham Palace", [["buck", "🦌", "A male deer"], ["ham", "🍖", "A joint of ham"], ["palace", "🏰", "A royal palace"]], "The London residence of the British monarch."],
  ],
  transport: [
    ["Airplane", [["air", "🌬️", "A gust of air"], ["plane", "✈️", "An aeroplane"]], "A vehicle that flies through the sky."],
    ["Sailboat", [["sail", "⛵", "A white sail"], ["boat", "🚤", "A small boat"]], "A wind-powered vessel."],
    ["Motorbike", [["motor", "⚙️", "A turning motor gear"], ["bike", "🚲", "A bicycle"]], "A powered two-wheeled vehicle."],
    ["Train Station", [["train", "🚆", "A passenger train"], ["station", "🚉", "A railway platform"]], "A place where rail passengers arrive and depart."],
    ["Fire Engine", [["fire", "🔥", "A bright fire"], ["engine", "🚒", "A fire engine"]], "An emergency vehicle used by firefighters."],
    ["Spaceship", [["space", "🌌", "Outer space filled with stars"], ["ship", "🚢", "A large ship"]], "A vehicle designed to travel beyond Earth."],
    ["School Bus", [["school", "🏫", "A school building"], ["bus", "🚌", "A yellow bus"]], "A vehicle that takes pupils to and from school."],
    ["Pickup Truck", [["pick", "⛏️", "A mining pick"], ["up", "⬆️", "An arrow pointing upwards"], ["truck", "🚚", "A truck"]], "A small truck with an open cargo area."],
    ["Underground", [["under", "⬇️", "An arrow pointing underneath"], ["ground", "🌱", "Green shoots growing from the ground"]], "An urban railway that runs below the streets."],
    ["Cable Car", [["cable", "🔌", "An electrical cable"], ["car", "🚗", "A car"]], "A vehicle pulled along by a cable."],
  ],
  objects: [
    ["Toothbrush", [["tooth", "🦷", "A white tooth"], ["brush", "🖌️", "A small brush"]], "An object used twice a day in the bathroom."],
    ["Sunglasses", [["sun", "☀️", "A bright sun"], ["glasses", "👓", "A pair of glasses"]], "Eyewear that shades your eyes."],
    ["Headphones", [["head", "🙂", "A smiling head"], ["phones", "📱", "Two mobile phones"]], "An object worn for private listening."],
    ["Notebook", [["note", "📝", "A handwritten note"], ["book", "📕", "A closed book"]], "A small book for writing ideas."],
    ["Doorbell", [["door", "🚪", "A wooden door"], ["bell", "🔔", "A ringing bell"]], "An object visitors press at an entrance."],
    ["Armchair", [["arm", "💪", "A strong arm"], ["chair", "🪑", "A chair"]], "A comfortable chair with supports at both sides."],
    ["Bookcase", [["book", "📕", "A closed book"], ["case", "💼", "A carrying case"]], "A piece of furniture used to store books."],
    ["Wallpaper", [["wall", "🧱", "A brick wall"], ["paper", "📄", "A sheet of paper"]], "Decorative covering applied to an indoor wall."],
    ["Keyring", [["key", "🔑", "A golden key"], ["ring", "💍", "A metal ring"]], "A small ring used to keep keys together."],
    ["Raincoat", [["rain", "🌧️", "A cloud releasing rain"], ["coat", "🧥", "A warm coat"]], "Waterproof clothing worn in wet weather."],
  ],
  brands: [
    ["Red Bull", [["red", "🟥", "A bright red square"], ["bull", "🐂", "A strong bull"]], "An energy-drink brand."],
    ["YouTube", [["you", "🫵", "A hand pointing at you"], ["tube", "🧪", "A glass tube"]], "A video-sharing brand."],
    ["PlayStation", [["play", "▶️", "A triangular play button"], ["station", "🚉", "A railway station"]], "A video game console brand."],
    ["Snapchat", [["snap", "🫰", "Fingers making a snap"], ["chat", "💬", "A speech bubble"]], "A picture-messaging brand."],
    ["KitKat", [["kit", "🧰", "A toolbox kit"], ["cat", "🐈", "A standing cat"]], "A chocolate-wafer brand."],
    ["Facebook", [["face", "🙂", "A smiling face"], ["book", "📕", "A closed book"]], "A social media brand."],
    ["Burger King", [["burger", "🍔", "A burger"], ["king", "👑", "A king's crown"]], "A fast-food restaurant brand."],
    ["LinkedIn", [["linked", "🔗", "Two linked chain loops"], ["in", "📥", "An arrow going into a tray"]], "A professional networking brand."],
    ["WhatsApp", [["what", "❓", "A question mark asking what"], ["app", "📱", "A smartphone app"]], "A messaging brand."],
    ["7UP", [["seven", "7️⃣", "The number seven"], ["up", "⬆️", "An arrow pointing upwards"]], "A lemon-and-lime soft drink brand.", ["Seven Up", "7 Up"]],
  ],
  "random-mix": [
    ["Moonwalk", [["moon", "🌙", "A crescent moon"], ["walk", "🚶", "A person walking"]], "A famous backward dance move."],
    ["Bookworm", [["book", "📕", "A closed book"], ["worm", "🪱", "A small worm"]], "Someone who loves reading."],
    ["Ladybird", [["lady", "👩", "A woman"], ["bird", "🐦", "A small bird"]], "A small red beetle with black spots."],
    ["Doorstep", [["door", "🚪", "A wooden door"], ["step", "👣", "A pair of footsteps"]], "The step immediately outside an entrance."],
    ["Brainstorm", [["brain", "🧠", "A human brain"], ["storm", "⛈️", "A thunderstorm cloud"]], "A lively burst of ideas."],
    ["Newspaper", [["new", "✨", "Bright new sparkles"], ["paper", "📄", "A clean sheet of paper"]], "Printed pages containing recent news."],
    ["Birthday", [["birth", "👶", "A newborn baby"], ["day", "📅", "A day on a calendar"]], "The anniversary of the day someone was born."],
    ["Lighthouse", [["light", "💡", "A glowing light bulb"], ["house", "🏠", "A house"]], "A tall coastal tower that guides ships."],
    ["Strawberry", [["straw", "🥤", "A drinking straw"], ["berry", "🫐", "A cluster of berries"]], "A small red fruit with seeds on the outside."],
    ["Shoelace", [["shoe", "👟", "A sports shoe"], ["lace", "🎀", "A tied lace bow"]], "A cord used to fasten a shoe."],
  ],
};

const difficultyPattern = (categoryIndex) => categoryIndex < 10
  ? [1, 1, 1, 2, 2, 1, 1, 2, 2, 3]
  : [1, 1, 2, 2, 3, 1, 1, 1, 2, 2];

const slugify = (value) => value.toLowerCase().replace(/['’]/g, "").replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");

export const rebuses = categories.flatMap((category, categoryIndex) =>
  definitions[category.id].map(([answer, rawClues, hint, variants = []], puzzleIndex) => ({
    id: `${category.id}-${slugify(answer)}`,
    category: category.id,
    answer,
    acceptedAnswers: [answer, ...variants],
    clues: rawClues.map(([word, emoji, alt]) => clue(word, emoji, alt)),
    hint,
    difficulty: difficultyPattern(categoryIndex)[puzzleIndex],
    imageStatus: "ready",
    approved: true,
  })),
);

export const categoryById = new Map(categories.map((category) => [category.id, category]));
